### ISSUE TITLE
PHP 7.4 Error - Deprecated Functionality: array_key_exists()

### ISSUE THREAD

**Issue by pauldonnelly** [Paymentsense-DevSupport/magento2-paymentsense-module#3]
It seems your module is breaking due to the function array_key_exists being deprecated. Can this be updated in your module.

"Deprecated Functionality: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in.."

**Comment by ghost** [comment]
We have this done. The version 2.4.0 of the module supporting PHP 7.4 is now available. It supports both Magento 2.3 and 2.4.

**Comment by pauldonnelly** [comment]
Thanks for this. I've tried to update via composer but it says there's nothing to update.
